export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const AUTHORIZED_ACCOUNT = 'AUTHORIZED_ACCOUNT';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const UNAUTHORIZED_ACCOUNT = 'UNAUTHORIZED_ACCOUNT';
export const EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER';
export const ENTITY_REGISTER_ERROR = 'ACCOUNT_REGISTER_ERROR';

export const REGION_ADDED = 'REGION_ADDED';
export const ADDING_REGION = 'ADDING_REGION';
export const ADDING_REGION_ERROR = 'ADDING_REGION_ERROR';

export const REGION_EDITED = 'REGION_EDITED';
export const EDITING_REGION = 'EDITING_REGION';
export const EDITING_REGION_ERROR = 'EDITING_REGION_ERROR';

export const REGIONS_FETCHED = 'REGIONS_FETCHED';
export const FETCHING_REGIONS = 'FETCHING_REGIONS';
export const FETCHING_REGIONS_ERROR = 'FETCHING_REGIONS_ERROR';

export const USER_ADDED = 'USER_ADDED';
export const ADDING_USER = 'ADDING_USER';
export const ADDING_USER_ERROR = 'ADDING_USER_ERROR';

export const USER_EDITED = 'USER_EDITED';
export const EDITING_USER = 'EDITING_USER';
export const EDITING_USER_ERROR = 'EDITING_USER_ERROR';

export const USERS_FETCHED = 'USERS_FETCHED';
export const FETCHING_USERS = 'FETCHING_USERS';
export const FETCHING_USERS_ERROR = 'FETCHING_USERS_ERROR';

export const MATERIALS_FETCHED = 'MATERIALS_FETCHED';
export const FETCHING_MATERIALS = 'FETCHING_MATERIALS';
export const FETCHING_MATERIALS_ERROR = 'FETCHING_MATERIALS_ERROR';

export const MATERIAL_COST_HISTORY_FETCHED = 'MATERIAL_COST_HISTORY_FETCHED';
export const FETCHING_MATERIAL_COST_HISTORY = 'FETCHING_MATERIAL_COST_HISTORY';
export const FETCHING_MATERIAL_COST_HISTORY_ERROR = 'FETCHING_MATERIAL_COST_HISTORY_ERROR';

export const MATERIAL_UNITS_OF_MEASUREMENT_FETCHED = 'MATERIAL_UNITS_OF_MEASUREMENT_FETCHED';
export const FETCHING_MATERIAL_UNITS_OF_MEASUREMENT_ERROR = 'FETCHING_MATERIAL_UNITS_OF_MEASUREMENT_ERROR';

export const MATERIAL_ADDED = 'MATERIAL_ADDED';
export const ADDING_MATERIAL = 'ADDING_MATERIAL';
export const ADDING_MATERIAL_ERROR = 'ADDING_MATERIAL_ERROR';

export const MATERIAL_UPDATED = 'MATERIAL_UPDATED';
export const UPDATING_MATERIAL_ERROR = 'UPDATING_MATERIAL_ERROR';

export const ADDING_COST_SHEET = 'ADDING_COST_SHEET'; 
export const COST_SHEET_ADDED = 'COST_SHEET_ADDED'; 
export const ADDING_COST_SHEET_ERROR = 'ADDING_COST_SHEET_ERROR'; 

export const FETCHING_COST_SHEETS = 'FETCHING_COST_SHEETS';
export const COST_SHEETS_FETCHED = 'COST_SHEETS_FETCHED';
export const FETCHING_COST_SHEETS_ERROR = 'FETCHING_COST_SHEETS_ERROR';


export const PROJECT_ADDED = 'PROJECT_ADDED';
export const ADDING_PROJECT = 'ADDING_PROJECT';
export const ADDING_PROJECT_ERROR = 'ADDING_PROJECT_ERROR';
export const PROJECT_EDITED = 'PROJECT_EDITED';
export const EDITING_PROJECT = 'EDITING_PROJECT';
export const EDITING_PROJECT_ERROR = 'EDITING_PROJECT_ERROR';
export const PROJECTS_FETCHED = 'PROJECTS_FETCHED';
export const FETCHING_PROJECTS = 'FETCHING_PROJECTS';
export const FETCHING_PROJECTS_ERROR = 'FETCHING_PROJECTS_ERROR';

export const TOOLS_FETCHED = 'TOOLS_FETCHED';
export const FETCHING_TOOLS = 'FETCHING_TOOLS';
export const FETCHING_TOOLS_ERROR = 'FETCHING_TOOLS_ERROR';
export const FETCHING_TOOL_COST_HISTORY = 'FETCHING_TOOL_COST_HISTORY';
export const TOOL_COST_HISTORY_FETCHED = 'TOOL_COST_HISTORY_FETCHED';
export const FETCHING_TOOL_COST_HISTORY_ERROR = 'FETCHING_TOOL_COST_HISTORY_ERROR';
export const TOOL_ADDED = 'TOOL_ADDED';
export const ADDING_TOOL = 'ADDING_TOOL';
export const ADDING_TOOL_ERROR = 'ADDING_TOOL_ERROR';
export const TOOL_UPDATED = 'TOOL_UPDATED';
export const UPDATING_TOOL_ERROR = 'UPDATING_TOOL_ERROR';
export const TOOL_DELETED = 'TOOL_DELETED';
export const DELETING_TOOL_ERROR = 'DELETING_TOOL_ERROR';

export const MATERIAL_DELETED = 'MATERIAL_DELETED';
export const DELETING_MATERIAL_ERROR = 'DELETING_MATERIAL_ERROR';

export const MANPOWERS_FETCHED = 'MANPOWERS_FETCHED';
export const FETCHING_MANPOWERS = 'FETCHING_MANPOWERS';
export const FETCHING_MANPOWERS_ERROR = 'FETCHING_MANPOWERS_ERROR';
export const FETCHING_MANPOWER_COST_HISTORY = 'FETCHING_MANPOWER_COST_HISTORY';
export const MANPOWER_COST_HISTORY_FETCHED = 'MANPOWER_COST_HISTORY_FETCHED';
export const FETCHING_MANPOWER_COST_HISTORY_ERROR = 'FETCHING_MANPOWER_COST_HISTORY_ERROR';
export const MANPOWER_ADDED = 'MANPOWER_ADDED';
export const ADDING_MANPOWER = 'ADDING_MANPOWER';
export const ADDING_MANPOWER_ERROR = 'ADDING_MANPOWER_ERROR';
export const MANPOWER_UPDATED = 'MANPOWER_UPDATED';
export const UPDATING_MANPOWER_ERROR = 'UPDATING_MANPOWER_ERROR';
export const MANPOWER_DELETED = 'MANPOWER_DELETED';
export const DELETING_MANPOWER_ERROR = 'DELETING_MANPOWER_ERROR';
export const MANPOWERS_JOBS_FETCHED = 'MANPOWERS_JOBS_FETCHED';
export const FETCHING_MANPOWERS_JOBS_ERROR = 'FETCHING_MANPOWERS_JOBS_ERROR';

export const COST_SHEET_FETCHED = 'COST_SHEET_FETCHED';
export const FETCHED_COST_SHEET_ERROR  = 'FETCHED_COST_SHEET_ERROR';

export const COST_SHEET_MATERIALS_FETCHED = 'COST_SHEET_MATERIALS_FETCHED';
export const FETCHED_COST_SHEET_MATERIALS_ERROR = 'FETCHED_COST_SHEET_MATERIALS_ERROR';


export const COST_SHEET_MANPOWER_FETCHED = 'COST_SHEET_MANPOWER_FETCHED';
export const FETCHED_COST_SHEET_MANPOWER_ERROR = 'FETCHED_COST_SHEET_MANPOWER_ERROR';

export const COST_SHEET_TOOLS_AND_EQUIPMENT_FETCHED = 'COST_SHEET_TOOLS_AND_EQUIPMENT_FETCHED';
export const FETCHED_COST_SHEET_TOOLS_AND_EQUIPMENT_ERROR = 'FETCHED_COST_SHEET_TOOLS_AND_EQUIPMENT_ERROR';