export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const AUTHORIZED_ACCOUNT = 'AUTHORIZED_ACCOUNT';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const UNAUTHORIZED_ACCOUNT = 'UNAUTHORIZED_ACCOUNT';
export const EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER';
export const ACCOUNT_REGISTER_ERROR = 'ACCOUNT_REGISTER_ERROR';


export const REGION_ADDED = 'REGION_ADDED';
export const ADDING_REGION = 'ADDING_REGION';
export const ADDING_REGION_ERROR = 'ADDING_REGION_ERROR';
export const REGION_EDITED = 'REGION_EDITED';
export const EDITING_REGION = 'EDITING_REGION';
export const EDITING_REGION_ERROR = 'EDITING_REGION_ERROR';
export const REGIONS_FETCHED = 'REGIONS_FETCHED';
export const FETCHING_REGIONS = 'FETCHING_REGIONS';
export const FETCHING_REGIONS_ERROR = 'FETCHING_REGIONS_ERROR';